### ISSUE TITLE
Issue with TTRPG NPC-template

### ISSUE THREAD

**Issue by shameforest** [BagOfTips/Community-TTRPG-Obsidian-Vault#2]
Hey all,

I am not sure if I am allowed to write here and ask questions about the template, so please tell me if this is a restricted area for coders-only :)

I installed the template which you advertised in your video on the BagOfTips channel. 
I am an Obsidian beginner, but already a bit familiar with  dataview. Didn't use Database Folder so far, only watched some videos. And I use the ITS Theme since a while already.
I have both plugins an the theme installed and activated.

When I grab your NPC Template and remove the ticks in the beginning and the end, the template looks a bit different (see image: left is your screenshot, right is my version):

https://imgur.com/a/0El0Lfq

What happened here? Why is my overview and the traits and personality stuff below the Bio-Box? When I go full screen with just this window, it is still the same. 
I want to have it like you next to each other.

Hope you can help me out.

Thanks in advance :)

Edit: When I try the same with your Settlement template, I get the same result. I double checked, I have all plugins installed. The ITS theme is installed also.

**Comment by BagOfTips** [comment]
> Hey all,
> 
> I am not sure if I am allowed to write here and ask questions about the template, so please tell me if this is a restricted area for coders-only :)
> 
> I installed the template which you advertised in your video on the BagOfTips channel. I am an Obsidian beginner, but already a bit familiar with dataview. Didn't use Database Folder so far, only watched some videos. And I use the ITS Theme since a while already. I have both plugins an the theme installed and activated.
> 
> When I grab your NPC Template and remove the ticks in the beginning and the end, the template looks a bit different (see image: left is your screenshot, right is my version):
> 
> https://imgur.com/a/0El0Lfq
> 
> What happened here? Why is my overview and the traits and personality stuff below the Bio-Box? When I go full screen with just this window, it is still the same. I want to have it like you next to each other.
> 
> Hope you can help me out.
> 
> Thanks in advance :)
> 
> Edit: When I try the same with your Settlement template, I get the same result. I double checked, I have all plugins installed. The ITS theme is installed also.

By all means, this area is for questions and issues if you have any!

Did you go to reading mode once you pasted them in?

**Comment by shameforest** [comment]
Yes, I am in reading mode. You can see the first infobox with the character pofile picture etc is placed on the right. But on the left there is empty space where should be the overview, traits, etc.

**Comment by BagOfTips** [comment]
> Yes, I am in reading mode. You can see the first infobox with the character pofile picture etc is placed on the right. But on the left there is empty space where should be the overview, traits, etc.

Mind attaching your note here and I will have a look

**Comment by shameforest** [comment]
[Template - NPC 1.md](https://github.com/BagOfTips/Community-TTRPG-Obsidian-Vault/files/10859668/Template.-.NPC.1.md)

Sure. But I only removed the ticks in the beginning and in the end.
I assume it has something to do with the callout functions of the ITS Theme?
Because when I write:
> [!infobox] blabla
it shows up on the right as it is supposed to be with the theme.
But I cannot reproduce the effect of having something left besides of the !infobox/character profile.

**Comment by BagOfTips** [comment]
> [Template - NPC 1.md](https://github.com/BagOfTips/Community-TTRPG-Obsidian-Vault/files/10859668/Template.-.NPC.1.md)
> 
> Sure. But I only removed the ticks in the beginning and in the end. I assume it has something to do with the callout functions of the ITS Theme? Because when I write:
> 
> > [!infobox] blabla
> 
> it shows up on the right as it is supposed to be with the theme. But I cannot reproduce the effect of having something left besides of the !infobox/character profile.

Loads just fine for me, I recommend checking all your Plugins and Appearance are up to date. Failing that, uninstall and re-install Obsidian and see if that fixes the issue

**Comment by shameforest** [comment]
Thank you. I disabled and enabled all plugins and found that the problem occured due to Style Settings, where I must have changed a setting in the last weeks. This fixed the problem for me:

Style Settings - ITS Theme - Note Elements - Center Headings - Center Heading Text (previously when problem occured: Center Heading with Lines)

Now the template looks as it supposed to be.

Thank you for the help.

**Comment by BagOfTips** [comment]
> Thank you. I disabled and enabled all plugins and found that the problem occured due to Style Settings, where I must have changed a setting in the last weeks. This fixed the problem for me:
> 
> Style Settings - ITS Theme - Note Elements - Center Headings - Center Heading Text (previously when problem occured: Center Heading with Lines)
> 
> Now the template looks as it supposed to be.
> 
> Thank you for the help.

Perfect, glad we got that sprted. Happy to help!
